services:
  mysql:
    image: mysql:8.0.32
    container_name: ${MYSQL_CONTAINER_NAME}
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  mysql:
